name: python3
channels:
  - conda-forge
dependencies:
  - python==3.9
  - pip==21.0.1
  - numpy==1.20.2
  - pandas==1.2.3
  - python-eccodes==2021.03.0
  - scipy==1.6.2
  - opencv==4.5.1
  - pip:
    - aiohttp==3.7.4.post0
    - blosc==1.10.2
    - fastapi[all]==0.63.0
    - gunicorn==20.1.0
    - opencv-python==4.5.1.48
    - opencv-contrib-python==4.5.1.48
    - jax==0.2.12
    - jaxlib==0.1.65
    - lz4==3.1.3
    - Pillow==8.2.0
    - uvicorn[standard]==0.13.4
